pipelines:
  branches: # Branch-specific pipelines definitions
    develop:
      - step:
          name: Build and test the app
          image: node:latest
          runs-on: ubuntu-latest 
          script:
            - docker build -t flakes-be ./
            
  