image: node:14.17.1

pipelines:
  branches: # Branch-specific pipelines definitions
    develop:
      - step:
          name: Build and test the app
          script:
            - docker build -t flakes-be ./
            
  